### ISSUE TITLE
Module doesn't work after Google play services are updated 

### ISSUE THREAD

**Issue by thelastbatman** [MrCarb0n/killgmsfont#2]
Everytime a new version of Google play services is updated from the play store, the fonts revert back to stock.

**Comment by MrCarb0n** [comment]
> Everytime a new version of Google play services is updated from the play store, the fonts revert back to stock.

What about after a system reboot?

**Comment by thelastbatman** [comment]
> > Everytime a new version of Google play services is updated from the play store, the fonts revert back to stock.
> 
> What about after a system reboot?

Yes it works after that. Since play services aftwr updated every few days it becomes quite cumbersome restarting so many times. Is restart only solution?

**Comment by MrCarb0n** [comment]
> > > Everytime a new version of Google play services is updated from the play store, the fonts revert back to stock.
> > 
> > 
> > What about after a system reboot?
> 
> Yes it works after that. Since play services aftwr updated every few days it becomes quite cumbersome restarting so many times. Is restart only solution?

I can integrate automation to resolve the issue. How frequently does GMS get updated? Any idea?

**Comment by thelastbatman** [comment]
> > > > Everytime a new version of Google play services is updated from the play store, the fonts revert back to stock.
> > > 
> > > 
> > > What about after a system reboot?
> > 
> > 
> > Yes it works after that. Since play services aftwr updated every few days it becomes quite cumbersome restarting so many times. Is restart only solution?
> 
> I can integrate automation to resolve the issue. How frequently does GMS get updated? Any idea?

Not fixed. Sometimes once a week and sometimes once a month. But on average 3-4 times a month
