### ISSUE TITLE
Can't install

### ISSUE THREAD

**Issue by thelastbatman** [MrCarb0n/killgmsfont#5]
Using magisk delta 26.4 on Android 13. 

After flashing version 1.5 it shows successful and reboot. But after reboot I see same version 1.0 only. It doesn't install 1.5 even though shows successful so i uninstalled 1.0 and then restarted. After than flashed 1.5 and guess what version 1.0 only installed . Please check.

**Comment by thelastbatman** [comment]
Awaiting response

**Comment by MrCarb0n** [comment]
#6
